FROM node:18.12.0-alpine

RUN npm install -g npm@8.8.0

ENV USER=app

ENV SUBDIR=appDir
ENV HOME=/home/$USER
WORKDIR $HOME/$SUBDIR

EXPOSE 3001
EXPOSE 3033

COPY .npmrc ./

COPY package.json ./
COPY package-lock.json ./
RUN npm ci

COPY ./server $HOME/$SUBDIR/server

ENV PATH $HOME/${SUBDIR}/node_modules/.bin:$PATH